name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Nodejs stuff
        run: echo $(node -v) > /github/home/test.txt
      - 
  dep:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: print stuff
        run: cat /github/home/test.txt
