name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Say something
        run: echo ${{ github.event_name }}
      - name: Say something, but not on pull_request
        if: github.event_name != 'pull_request'
        run: echo ${{ github.event_name }}
      - name: How commits were pushed
        run: echo ${{ github.event.commits.length }}
