name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: ping 127.0.0.1 -n6 -w 500 > NUL
      - run: choice /t 0.5 /d y > NUL
