name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - uses: gustavohenke/test-repo@649bed38df4a99ba33f966ec39c82374d19b4838
      - name: List repo
        run: ls -l
