name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
#   build:
#     runs-on: windows-latest
#     steps:
#       - run: ping 127.0.0.1 -n 6 -w 500 > NUL
#       - run: waitfor something /t 0.5
#       # - run: choice /t 0.5 /d y
#   set-output:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo '::set-output name=FOO::bla bla bla'
#         id: set-foo
#       - run: echo "The value of FOO is ${{ steps.set-foo.outputs.FOO }}"
  corepack_pnpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # - run: which corepack && corepack enable && corepack prepare --activate pnpm@8
      - run: which pnpm && pnpm -v
  pnpm_only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: which pnpm && pnpm -v
  push-length:
    runs-on: ubuntu-latest
    steps:
      - env:
          COMMITS: ${{ toJSON(github.event.commits) }}
        run: echo "::set-output name=value::$(( $(echo "$COMMITS" | jq length) + 1 ))"
        id: push-depth
      - uses: actions/checkout@v2
        with:
          fetch-depth: ${{ github.event.pull_request.commits || steps.push-depth.outputs.value }}
